services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - seo-network
    depends_on:
      - db
    command: php-fpm

  web:
    image: nginx:alpine
    container_name: seo-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - seo-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: seo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    networks:
      - seo-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: seo-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db  # Name of the database container
      PMA_USER: laravel_user  # MySQL root username
      PMA_PASSWORD: laravel_password  # MySQL root password
      PMA_ARBITRARY: 1
      APACHE_SERVER_NAME: phpmyadmin.local
    depends_on:
      - db
    networks:
      - seo-network

  node:
    image: node:18
    container_name: seo-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - seo-network
    command: tail -f /dev/null

  redis:
    image: redis:alpine
    container_name: seo-redis
    ports:
      - "6379:6379"
    networks:
      - seo-network


volumes:
  db-data:

networks:
  seo-network:
    driver: bridge
